version: "3.7"

services:

  # bot
  douyintgbot:
    image: jwstar/douyintgbot:latest
    network_mode: host
    container_name: douyintgbot
    restart: always
    environment:
      TZ: Asia/Shanghai
      #正式
      API_ID: 7747911111135
      API_HASH: 111111
      BOT_TOKEN: 11:111
      CHANNEL_ID: -10255555555

    deploy:
      resources:
        limits:
          cpus: '0.80'