version: "3.7"

services:

  # bot
  douyintgbot:
    image: jwstar/douyintgbot:latest
    network_mode: host
    container_name: douyintgbot
    restart: always
    environment:
      TZ: Asia/Shanghai
      #正式
      API_ID: 7747935
      API_HASH: 7d98fa6e83d0d43541fa97bfb6d58f1e
      BOT_TOKEN: 5161622943:AAF1tQwms_Ns_tiB1Vx6wNC5O13Gdq_jkq4

    deploy:
      resources:
        limits:
          cpus: '0.80'